### ISSUE TITLE
Precios de los productos del armario

### ISSUE THREAD

**Issue by Ironjanowar** [acmfi/acm_bot#4]
**Is your feature request related to a problem? Please describe.**
Para no tener que preguntar a nadie o tener que ir al armario a ver los precios, el bot puede los precios de lo que hay en el armario.

**Describe the solution you'd like**
Lo ideal sería implementar la posibilidad de ver los precios de manera inline, de tal manera que escribiendo `@acmupm_bot galletas`, se hiciera una búsqueda entre los productos y mostrar una pequeña lista con los mejores resultados de esa búsqueda.

La lista podría tener un formato tipo:
```
producto1   0.60€
producto2   1.20€
producto3   0.40€
```

Además se podrá clicar en cualquiera de ellos para compartir esa información.

Si además se quiere toda la lista al poner `@acmupm_bot` sin ningúna búsqueda saldrán las opciones:
```
Productos del armario
```

Al clicar en esta opción se mostrará en el chat la lista completa de los precios.

**Describe alternatives you've considered**
De momento solo se me ha ocurrido esto.

**Additional context**
Para esto estaría bien tener una base de datos para que sea mucho más sencilla la implementación. Si actualmente se guardan los precios en un excel se podría exportar a csv e introducirlos en una base de datos que consuma el bot.

Esto se puede automatizar mediante scripts también e incluso se puede añadir un comando de administrador en el bot para hacer ese volcado, aunque esto recomiendo que se plantee una vez esté implementado esta funcionalidad.

**Comment by Alfedi** [comment]
**Alternativas**
Considero que sería mucho más fácil subir el pdf con los precios del armario y actualizarlo cada vez que se compre. A corto plazo me parece la mejor solución para tener disponible este comando y más adelante se puede implementar la idea de @Ironjanowar.
