### ISSUE TITLE
Enhance the /armario command

### ISSUE THREAD

**Issue by Ironjanowar** [acmfi/acm_bot#6]
**The problem**
The bot sends the same document every time you ask for it.

**Suggestion**
Use an application env variable to store (in execution) the file id sent with `ExGram.send_document( ... )`

**Comment by Ironjanowar** [comment]
@Alfedi, @rockneurotiko suggested not ussing an env variable for this.
Insead you could create a `GenServer` to store the `file_id`, and it could be used as a cache later.

Thanks @rockneurotiko

**Comment by Alfedi** [comment]
Wow. Serious business. I don't know anything about `GenServer` but I'll try my best.
